services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - my_network

  features:
    build:
      context: ./features
    restart: always
    depends_on:
      - rabbitmq
    networks:
      - my_network

  model:
    build:
      context: ./model
    restart: always
    depends_on:
      - rabbitmq
      - features
    networks:
      - my_network

  metric:
    build:
      context: ./metric
    restart: always
    depends_on:
      - rabbitmq
      - features
      - model
    volumes:
      - ./metric/logs:/metric/logs
    networks:
      - my_network

  plot:
    build:
      context: ./plot
    restart: always
    depends_on:
      - rabbitmq
      - features
      - model
      - metric
    volumes:
      - ./metric/logs:/metric/logs
    networks:
      - my_network

networks:
  my_network:
    driver: bridge